name: CI datetime job 

on:
  push:
    branches: 
    - "**"
  pull_request:
    branches: 
    - "**"

jobs:
  show-datetime:
    runs-on: ubuntu-latest
    steps:
      - name: Show current date and time
        run: |
          echo "Current date and time:"
          date
